version: 2
updates:
  - package-ecosystem: npm
    directory: /consumer-sdk
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /consumer-app
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /examples/next-openfeature
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
